import type { User, Chat, Message } from './types'

export const mockUsers: Record<string, User> = {
  current_user: {
    id: 'user_1',
    username: 'yourname',
    displayName: 'Your Name',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop',
    pronouns: 'they/them',
    about: 'Designer & Developer',
    online: true,
    lastSeen: new Date().toISOString(),
  },
  user_2: {
    id: 'user_2',
    username: 'alex.designer',
    displayName: 'Alex',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
    pronouns: 'he/him',
    about: 'Product Designer',
    online: true,
    lastSeen: new Date().toISOString(),
  },
  user_3: {
    id: 'user_3',
    username: 'sam.engineer',
    displayName: 'Sam',
    avatar: 'https://images.unsplash.com/photo-1517070213482-c5377cdc5340?w=100&h=100&fit=crop',
    pronouns: 'she/her',
    about: 'Full Stack Developer',
    online: true,
    lastSeen: new Date(Date.now() - 5 * 60000).toISOString(),
  },
  user_4: {
    id: 'user_4',
    username: 'jordan.pm',
    displayName: 'Jordan',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&h=100&fit=crop',
    pronouns: 'he/him',
    about: 'Product Manager',
    online: false,
    lastSeen: new Date(Date.now() - 60 * 60000).toISOString(),
  },
  user_5: {
    id: 'user_5',
    username: 'emma.marketing',
    displayName: 'Emma',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop',
    pronouns: 'she/her',
    about: 'Marketing Lead',
    online: true,
    lastSeen: new Date().toISOString(),
  },
}

export const mockMessages: Record<string, Message[]> = {
  chat_1: [
    {
      id: 'msg_1',
      chatId: 'chat_1',
      senderId: 'user_2',
      content: 'Hey! How are you doing?',
      type: 'text',
      timestamp: new Date(Date.now() - 20 * 60000),
      status: 'seen',
      visibility: 'forever',
      isEncrypted: true,
      reactions: { '😂': 1 }
    },
    {
      id: 'msg_2',
      chatId: 'chat_1',
      senderId: 'user_1',
      content: 'Hey Alex! Doing great, just working on the new design system. How about you?',
      type: 'text',
      timestamp: new Date(Date.now() - 18 * 60000),
      status: 'seen',
      visibility: 'forever',
      isEncrypted: true,
    },
    {
      id: 'msg_3',
      chatId: 'chat_1',
      senderId: 'user_2',
      content: 'That sounds cool! Can\'t wait to see it. Do you have time for a quick call later?',
      type: 'text',
      timestamp: new Date(Date.now() - 5 * 60000),
      status: 'delivered',
      visibility: 'forever',
      isEncrypted: true,
    },
  ],
  chat_2: [
    {
      id: 'msg_4',
      chatId: 'chat_2',
      senderId: 'user_3',
      content: 'Did you check the PR I sent?',
      type: 'text',
      timestamp: new Date(Date.now() - 2 * 3600000),
      status: 'seen',
      visibility: 'forever',
      isEncrypted: true,
    },
    {
      id: 'msg_5',
      chatId: 'chat_2',
      senderId: 'user_1',
      content: 'Yes! Looks good, just had a few minor comments',
      type: 'text',
      timestamp: new Date(Date.now() - 1 * 3600000),
      status: 'seen',
      visibility: 'forever',
      isEncrypted: true,
    },
  ],
  chat_3: [
    {
      id: 'msg_6',
      chatId: 'chat_3',
      senderId: 'user_4',
      content: 'Team meeting tomorrow at 10 AM?',
      type: 'text',
      timestamp: new Date(Date.now() - 12 * 3600000),
      status: 'seen',
      visibility: 'forever',
      isEncrypted: true,
    },
  ],
  chat_4: [
    {
      id: 'msg_7',
      chatId: 'chat_4',
      senderId: 'user_5',
      content: 'The campaign numbers look amazing!',
      type: 'text',
      timestamp: new Date(Date.now() - 1 * 3600000),
      status: 'seen',
      visibility: 'forever',
      isEncrypted: true,
    },
    {
      id: 'msg_8',
      chatId: 'chat_4',
      senderId: 'user_1',
      content: 'Right? We should celebrate! 🎉',
      type: 'text',
      timestamp: new Date(Date.now() - 30 * 60000),
      status: 'seen',
      visibility: 'forever',
      isEncrypted: true,
    },
  ],
  chat_5: [
    {
      id: 'msg_9',
      chatId: 'chat_5',
      senderId: 'user_2',
      content: 'Let\'s catch up soon!',
      type: 'text',
      timestamp: new Date(Date.now() - 24 * 3600000),
      status: 'delivered',
      visibility: 'forever',
      isEncrypted: true,
    },
  ],
}

export const mockChats: Chat[] = [
  {
    id: 'chat_1',
    type: 'dm',
    name: 'Alex',
    avatar: mockUsers.user_2.avatar,
    lastMessage: mockMessages.chat_1[mockMessages.chat_1.length - 1],
    unreadCount: 1,
    participants: [mockUsers.user_1, mockUsers.user_2],
    archived: false,
    hidden: false,
    messages: mockMessages.chat_1,
    typingUsers: [],
    createdAt: new Date(Date.now() - 30 * 24 * 3600000),
  },
  {
    id: 'chat_2',
    type: 'dm',
    name: 'Sam',
    avatar: mockUsers.user_3.avatar,
    lastMessage: mockMessages.chat_2[mockMessages.chat_2.length - 1],
    unreadCount: 0,
    participants: [mockUsers.user_1, mockUsers.user_3],
    archived: false,
    hidden: false,
    messages: mockMessages.chat_2,
    typingUsers: [],
    createdAt: new Date(Date.now() - 20 * 24 * 3600000),
  },
  {
    id: 'chat_3',
    type: 'group',
    name: 'Team Sync',
    avatar: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=100&h=100&fit=crop',
    lastMessage: mockMessages.chat_3[mockMessages.chat_3.length - 1],
    unreadCount: 0,
    participants: [mockUsers.user_1, mockUsers.user_2, mockUsers.user_3, mockUsers.user_4],
    archived: false,
    hidden: false,
    messages: mockMessages.chat_3,
    typingUsers: [],
    createdAt: new Date(Date.now() - 60 * 24 * 3600000),
  },
  {
    id: 'chat_4',
    type: 'group',
    name: 'Project Horizon',
    avatar: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=100&h=100&fit=crop',
    lastMessage: mockMessages.chat_4[mockMessages.chat_4.length - 1],
    unreadCount: 0,
    participants: [mockUsers.user_1, mockUsers.user_5, mockUsers.user_2],
    archived: false,
    hidden: false,
    messages: mockMessages.chat_4,
    typingUsers: [],
    createdAt: new Date(Date.now() - 45 * 24 * 3600000),
  },
  {
    id: 'chat_5',
    type: 'dm',
    name: 'Jordan',
    avatar: mockUsers.user_4.avatar,
    lastMessage: mockMessages.chat_5[mockMessages.chat_5.length - 1],
    unreadCount: 2,
    participants: [mockUsers.user_1, mockUsers.user_4],
    archived: false,
    hidden: true,
    hiddenPassword: 'secret123',
    messages: mockMessages.chat_5,
    typingUsers: [],
    createdAt: new Date(Date.now() - 100 * 24 * 3600000),
  },
]
